name: Generate Datas

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: devthiagoporto
          svg_out_path: dist/github-contribution-grid-snake.svg
      - uses: crazy
